version: "3"
services: 
  webapp: 
    build: 
      context: /root
      dockerfile: Dockerfile
    image: darshannginx
    ports: 
      - "8080:80"
    networks: 
      - webnet

networks: 
  webnet:
